name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} 🟢
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install 🔧
        run: npm ci
      - name: Test 🚨
        run: npm test
